version: '3.7'

services:
  db:
    build: ./db
    container_name: spark-loader-web-2-db
    ports:
      - "5433:5432"
    env_file:
      - ./.env.dev.db

  app:
    build: ./app
    container_name: spark-loader-web-2
    command: sh -c "/home/app/web/run_server.sh"
    depends_on:
      - db
    volumes:
      - ./app/loaders:/usr/src/app/web/sparkLoaderWeb2/security
      - ./app/security:/usr/src/app/web/sparkLoaderWeb2/loaders
    expose:
      - 8000
    env_file:
      - ./.env.dev

  nginx:
    build: ./nginx
    container_name: spark-loader-web-2-nginx
    ports:
      - "1337:80"
    depends_on:
      - app

volumes:
  static_volume:
